language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t dadofbear/udagram-api-feed:v01 ./udagram-api-feed
  - docker build -t dadofbear/udagram-api-user:v01 ./udagram-api-user
  - docker build -t dadofbear/udagram-frontend:v01 ./udagram-frontend
  - docker build -t dadofbear/reverseproxy:v01 ./udagram-reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dadofbear/udagram-api-feed:v01
  - docker push dadofbear/udagram-api-user:v01
  - docker push dadofbear/udagram-frontend:v01
  - docker push dadofbear/reverseproxy:v01