apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    # nodePort: 30003
  selector:
    service: reverseproxy
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: dadofbear/reverseproxy:latest
        name: reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
